/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Courses: () => import('#controllers/courses_controller'),
  Enrollments: () => import('#controllers/enrollments_controller'),
  Grades: () => import('#controllers/grades_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Submissions: () => import('#controllers/submissions_controller'),
}
